//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyExecution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class organisationdatabaseEntities : DbContext
    {
        public organisationdatabaseEntities()
            : base("name=organisationdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buildingdetail> buildingdetails { get; set; }
        public virtual DbSet<classdetail> classdetails { get; set; }
        public virtual DbSet<floordetail> floordetails { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<schedulereserve> schedulereserves { get; set; }
        public virtual DbSet<scheduletransfer> scheduletransfers { get; set; }
        public virtual DbSet<sectionsinfo> sectionsinfoes { get; set; }
        public virtual DbSet<semesterinfo> semesterinfoes { get; set; }
        public virtual DbSet<strategyequipment> strategyequipments { get; set; }
        public virtual DbSet<strategymanagement> strategymanagements { get; set; }
        public virtual DbSet<systemsetting> systemsettings { get; set; }
        public virtual DbSet<strategydescription> strategydescriptions { get; set; }
    }
}
