//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class machineworkinghour
    {
        public string IP { get; set; }
        public int location { get; set; }
        public System.DateTime date { get; set; }
        public double projectorHour { get; set; }
        public double pcHour { get; set; }
        public double recorderHour { get; set; }
        public double ACHour { get; set; }
        public double systemHour { get; set; }
        public Nullable<double> screenHour { get; set; }
    }
}
