//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class organisationdatabaseEntities : DbContext
    {
        public organisationdatabaseEntities()
            : base("name=organisationdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alarmmonitorlog> alarmmonitorlogs { get; set; }
        public virtual DbSet<buildingdetail> buildingdetails { get; set; }
        public virtual DbSet<cameramonitorinfo> cameramonitorinfoes { get; set; }
        public virtual DbSet<classdetail> classdetails { get; set; }
        public virtual DbSet<machineoperationlog> machineoperationlogs { get; set; }
        public virtual DbSet<strategydescription> strategydescriptions { get; set; }
        public virtual DbSet<strategyequipment> strategyequipments { get; set; }
        public virtual DbSet<strategylog> strategylogs { get; set; }
        public virtual DbSet<strategymanagement> strategymanagements { get; set; }
        public virtual DbSet<temp_machinestatus> temp_machinestatus { get; set; }
        public virtual DbSet<temp_desktopevents> temp_desktopevents { get; set; }
        public virtual DbSet<card_registration> card_registration { get; set; }
        public virtual DbSet<cardlog> cardlogs { get; set; }
        public virtual DbSet<machineusagelogs_minute> machineusagelogs_minute { get; set; }
        public virtual DbSet<projectorconfiginfo> projectorconfiginfoes { get; set; }
    }
}
