//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public int SerialNo { get; set; }
        public string LoginID { get; set; }
        public string UserName { get; set; }
        public string PersonType { get; set; }
        public string PersonnelStatus { get; set; }
        public string Notes { get; set; }
        public string Password { get; set; }
        public string phone { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime expireDate { get; set; }
    }
}
